AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resolver testing Lambda.

Globals:
  Function:
    Runtime: python3.11
    Timeout: 60
    MemorySize: 256

Parameters:
  DefaultTarget:
    Type: String
    Default: example.com
    Description: Default domain to test if none supplied in the event.
  FailDnsLogBucket:
    Type: String
    Description: S3 bucket for failure logs (must already exist).

Resources:
  ResolverTestingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: resolver-testing
      Handler: lambda_function.lambda_handler
      CodeUri: .
      Environment:
        Variables:
          DEFAULT_TARGET: !Ref DefaultTarget
          FAIL_DNS_LOG_BUCKET: !Ref FailDnsLogBucket
          S3_PREFIX: logs/resolver_failures/
      Policies:
        - S3WritePolicy:
            BucketName: !Ref FailDnsLogBucket

Outputs:
  FunctionName:
    Description: Name of Lambda function
    Value: !Ref ResolverTestingFunction
  FunctionArn:
    Description: ARN of Lambda function
    Value: !GetAtt ResolverTestingFunction.Arn
